### ISSUE TITLE
Malik & Debby - Implement unsigned user flow

### ISSUE THREAD

**Issue by DeborahIhesiaba** [annonymousauthority/P2PCoder#136]
## Todo

- [x] Create language modal
- [x] Link addFile button to the language modal
- [x] Add a run button after user has created at least one tab
- [x] Add tab with respective language name, icon,  and editor
- [x] Add sign up and login buttons to top nav
- [x] Add toast error message at tab limit of 5
